### ISSUE TITLE
Question： how to preprocess the MovieLens-1M dataset

### ISSUE THREAD

**Issue by jjkk123456** [YunjiaXi/Open-World-Knowledge-Augmented-Recommendation#1]
Hello, it seems that the code repository currently only has preprocessing code for the Amazon dataset. I was wondering if you could provide preprocessing code for the MovieLens-1M dataset.

**Comment by YunjiaXi** [comment]
Now the preprocessing code for MovieLens-1M is available [here](https://github.com/YunjiaXi/Open-World-Knowledge-Augmented-Recommendation/blob/main/preprocess/preprocess_ml-1m.py).
